### ISSUE TITLE
errors on the first two clicks on a multi select

### ISSUE THREAD

**Issue by matheusdavidson** [PolymerElements/paper-menu#10]
Trying out the demo i get an error in the first two clicks on a multi select, first time i click, selecting one option it shows this:
Uncaught TypeError: focusedItem.setAttribute is not a function
Then when i click second time:
Uncaught TypeError: old.setAttribute is not a function

Items are still selected even after the errors.

**Comment by morethanreal** [comment]
I cannot reproduce this issue.
