### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by BorntraegerMarc** [PolymerElements/paper-menu#116]
At least add a deprecation notice in the README so that everybody knows, that the element is not supported anymore.

**Comment by a8775** [comment]
What component could be used in place of the paper-menu to get the submenu functionality?
Is any example available?

**Comment by balloob** [comment]
According to [this convo on Slack](https://polymer.slack.com/archives/C03PF4L4L/p1495733953165575) it is suggested to use paper-listbox instead.

**Comment by phidias51** [comment]
The proper way to deprecate code is to use the @deprecated annotation and to point the user to the replacement component. Ideally the build process/linter should point out when you're using deprecated code, so that you can update your code accordingly.

**Comment by notwaldorf** [comment]
Added a note!
