### ISSUE TITLE
Accessibility issue: ENTER does not activate menu item

### ISSUE THREAD

**Issue by jannakha** [PolymerElements/paper-menu#19]
From documentation: "It implements key bindings to navigate through the menu with the up and down arrow keys, esc to exit the menu, and enter to activate a menu item. Typing the first letter of a menu item will also focus it."

Neither SPACE nor ENTER activate menu item, same issue with paper-tabs (pressing ENTER does not activate selected tab, although it activates paper-ripple)

**Comment by morethanreal** [comment]
Which browser and version do you see this issue on?

**Comment by jannakha** [comment]
Doesn't work in Chrome 43, latest Safari 8.0.6, FireFox 38
here's demo:
https://elements.polymer-project.org/elements/paper-menu?view=demo:demo/index.html
when you hit enter - paper-item does not get selected, but when you click on an item - it does get selected. Same with paper-tabs, haven't tested other component yet.

**Comment by morethanreal** [comment]
Appears to be a dup of https://github.com/PolymerElements/paper-tabs/issues/28.
