### ISSUE TITLE
Background flicker when changing selection

### ISSUE THREAD

**Issue by Ortham** [PolymerElements/paper-menu#20]
The background of the previous selection flickers whenever a menu item is selected for the first time. The flicker occurs when the left (or right) mouse button is pressed, before it is released. I can replicate this on the [demo page](https://elements.polymer-project.org/elements/paper-menu?view=demo:demo/index.html), on Chrome 43, Firefox 38 and IE 11.

**Comment by morethanreal** [comment]
The fix is to set `tabindex=-1` on all the distributed children.

**Comment by notwaldorf** [comment]
Closing as this element has changed a lot, and it doesn't seem to be reproducible. Please re-open if it's still an issue
