### ISSUE TITLE
Documentation doesn't explain how to set selection programatically.

### ISSUE THREAD

**Issue by grokys** [PolymerElements/paper-menu#23]
Or in markup. Is it possible? Using the syntax for iron-selector doesn't appear to work.

EDIT: Ah, you can find it by looking at the behavior. Ok, it is documented, but might be helpful to provide an example and a pointer as to where to look?

**Comment by notwaldorf** [comment]
Thanks, that's good feedback. I will add a little blurb in the docs :)

**Comment by Mipme** [comment]
What's also missing is how to clear the selection. Couldn't find a way to achieve this...

**Comment by Mipme** [comment]
Well, some fiddling around let me achieve how to clear the selection on a paper-menu. `paperMenuElement.select(null)` seems to work. Also, this is not firing the `iron-select` event, so if the `paper-menu` for instance is used in a `paper-dropdown-menu` the `selectedItem` of that element remains. So for now its advisable to trigger this event manually...
