### ISSUE TITLE
attrForSelected in paper-menu

### ISSUE THREAD

**Issue by grokys** [PolymerElements/paper-menu#24]
Should the attrForSelected stuff from `IronSelectableBehavior` work with `paper-menu`? It doesn't appear to, see the following jsbin:

http://jsbin.com/yemoxuvili/edit?html,console,output

**Comment by notwaldorf** [comment]
You need to use `attr-for-selected`, since you're using the attribute in HTML. Does that fix your issue?

**Comment by grokys** [comment]
Indeed it does @notwaldorf - thank you. I'd apparently forgottten that part of the docs, though I do vaguely remember reading it. Thanks for your help. Maybe something else that could be added as an example to the paper-menu docs?
