### ISSUE TITLE
Building Submenu in paper-menu

### ISSUE THREAD

**Issue by mojtabashabani** [PolymerElements/paper-menu#26]
in 0.5 version we can build sub menu with core-menu and core-submenu
Where is Paper-submenu?

**Comment by stellirin** [comment]
I was also looking for sub menus.

**Comment by shashi** [comment]
https://github.com/PolymerElements/paper-menu/commit/901b0f580358c2f42d3f99cf2759c35fb310a045 fixes this :) :+1:

**Comment by notwaldorf** [comment]
Yup, this has landed in the last `paper-menu` release.
