### ISSUE TITLE
2 taps needed on Paper-Menu on Firefox 38.0.5  Only one on Chrome and IE

### ISSUE THREAD

**Issue by MarkDurbin104** [PolymerElements/paper-menu#27]
**Neither the selected or the on-iron-activate are triggered until second tap on Firefox.**

``` HTML
<paper-menu id="menu" class="list" attr-for-selected="data-route" selected="{{route}}" on-iron-activate="_listTap" >
  <template is="dom-repeat" items="{{subjects}}">
    <paper-item data-route$="{{item.page}}" >
      <iron-icon icon="{{item.icon}}"></iron-icon> <span>{{item.text}}</span>
    </paper-item>
  </template>
</paper-menu>
```

**Comment by realistschuckle** [comment]
This also happens in Safari.

**Comment by chuckh** [comment]
You can also see this behavior with paper-menu demo when using Safari or Firefox at https://elements.polymer-project.org/elements/paper-menu?view=demo:demo/index.html.

**Comment by rubenstolk** [comment]
`pointer-events` to the rescue, this at least solves the issue although I think it should be solved within `paper-menu` or `paper-item` itself:

```
paper-menu paper-item > *, paper-menu paper-icon-item > * {
  pointer-events: none;
}
```

**Comment by chuckh** [comment]
@rubenstolk thanks for the work around. To fix Polymer Starter Kit also add `paper-menu a > *,`

```
paper-menu a > *, paper-menu paper-item > *, paper-menu paper-icon-item > * {
  pointer-events: none;
}
```

**Comment by rubenstolk** [comment]
Is anyone going to come up with an acceptable solution here? @cdata? Is it clear to everyone that this issue also affects Safari on Mac, which is a very commonly used browser still...?

**Comment by a8775** [comment]
I had the same problem. @rubenstolk thanks for the solution, it worked for me.

**Comment by cdata** [comment]
Sorry for letting this one linger guys. I will take a look.

**Comment by binoculars** [comment]
:+1: Same issue on OS X Safari 9.0.2, but the CSS from @rubenstolk is a workaround.
