### ISSUE TITLE
on-iron-activate indexes start at 1

### ISSUE THREAD

**Issue by BLamy** [PolymerElements/paper-menu#36]
I'm playing around with this example.
https://github.com/PolymerElements/app-layout-templates/blob/master/nav-list-detail/src/x-app.html

I've noticed that when the list is clicked it calls _listTap
`on-iron-activate="_listTap"`

I modified my function to look like this

``` javascript
_listTap: function(event, target) {
   console.log(target.selected);
}
```

If I click the first item in the list it prints 1. Wouldn't the intended behavior start counting at 0?

**Comment by frankiefu** [comment]
Hmm... I got `0` for the first item.  Could you double check your finding?

<img width="1024" alt="screen shot 2015-08-17 at 5 38 19 pm" src="https://cloud.githubusercontent.com/assets/116360/9319759/d66e0240-4506-11e5-8ffe-da04d4e6ffb7.png">

**Comment by bicknellr** [comment]
After looking into this a bit more, I think I found the result of the confusion: `iron-activate` is fired _before_ the `selected` property of the menu changes. ([Here's where it happens in iron-selector.](https://github.com/PolymerElements/iron-selector/blob/e65708e8bd1ebbb53fed8de6c7ce208c9443d823/iron-selectable.html#L318)) This is meant to allow you to cancel the `iron-activate` event, and prevent the selection from occurring. (And therefore preventing `iron-select` and `selected-changed` from firing.) [Take a look at this test](http://jsbin.com/jodebic/edit?html,output), it's a modified version of the x-app example. If you click through items in the list, you'll notice that `selectedDuringOnIronActivate` is always one step behind `selectedDuringOnSelectedChanged`.
