### ISSUE TITLE
Pressing <Enter> on a menu item doesn't select it

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-menu#40]
This is probably related to https://github.com/PolymerElements/paper-tabs/issues/28

**Comment by danbeam** [comment]
this blocks the new polymer chrome://downloads from being launched, btw

**Comment by robdodson** [comment]
+1 this is preventing me from switching to paper-item in my menu

**Comment by samccone** [comment]
xref  PolymerElements/iron-selector#36

**Comment by danbeam** [comment]
is this now fixed as of [`45e4ba8`](https://github.com/PolymerElements/iron-selector/commit/45e4ba87c62daeaab4e481a99a62780ffd17b0b6)?

**Comment by japacible** [comment]
Friendly ping @tjsavage

Related: is it expected for spacebar to select a menu item as well? PolymerElements/iron-menu-behavior#14

In the [demo](http://output.jsbin.com/bitozu), it looks like pressing <enter> now selects a menu item but not spacebar.

**Comment by dfreedm** [comment]
@japacible pressing enter and space seem to be working in that demo for me, maybe something has changed in the past week?

**Comment by dfreedm** [comment]
@cdata says that https://github.com/PolymerElements/paper-item/pull/27 + https://github.com/PolymerElements/iron-menu-behavior/pull/25 together should account for paper-items being keyboard accessible now, yay!
