### ISSUE TITLE
paper-menu fails to hide after data change and selection 

### ISSUE THREAD

**Issue by ghost** [PolymerElements/paper-menu#46]
When clicking an item that is already selected in the paper-menu, the menu doesn't automatically hide itself. In my application the data in the menu changes from time to time. When you open the menu after a data change an item is already highlighted as if selected, and when you click it the paper-menu doesn't hide itself.

**Comment by kevinpschaaf** [comment]
`paper-menu` doesn't include a dialog that hides itself, so it's hard to understand your setup.  Please re-open if you're still having this problem, and include a jsBin that reproduces the issue per the [contributing guide](https://github.com/PolymerElements/paper-menu/blob/master/CONTRIBUTING.md).
