### ISSUE TITLE
Dynamic recursive menu does not work

### ISSUE THREAD

**Issue by maxiplay** [PolymerElements/paper-menu#47]
Hi, 

I try to code a component that do a recursive call based on data from table.

With static way it work, but with recursive no.

I have done a plunker 

http://plnkr.co/edit/KqR3X5PKfuTKq7oNgTvO

**Comment by bicknellr** [comment]
Hi @maxiplay, inside `recursive-menu-element`, if you change `nested-menu-element` to `recursive-menu-element` and add `class="menu-content"` to it, it works. [Here's an updated version of your demo.](http://plnkr.co/edit/gmm1fJQYizLPgLunUpNA)

**Comment by maxiplay** [comment]
My differents test drive me to use an element (nested-menu-element) who did not exist^^ Thank you.
I had stopped to work on this waiting a response (long time). Now I will can continue :)
