### ISSUE TITLE
Menu scrolls around on select

### ISSUE THREAD

**Issue by Evanfeenstra** [PolymerElements/paper-menu#54]
``` html
<paper-menu selectable=".item">
  <paper-item class="item" on-tap="open">...</paper-item>
  <iron-collapse>...</iron-collapse>
  ...
<paper-menu>
```

Each paper-item in my paper-menu opens the iron-collapse below it. Tapping anywhere within the iron-collapse content will focus and scroll to the paper-item above it. 

Adding "e.preventDefault()" to on-down events of the iron-collapse elements fixes this for mouse events, but not for touch events. Is there another way to prevent focus and scroll?

**Comment by kevinpschaaf** [comment]
`paper-menu` is designed such that all children should be selectable (focusable) items.  Here you have 2 elements per one "selectable" item.  Instead, wrap them in a container, e.g. div, and you should avoid the behavior you described: http://jsbin.com/xazuxeheji/edit?html,console,output
