### ISSUE TITLE
Although README mentions paper-submenu, the docs don't

### ISSUE THREAD

**Issue by akc42** [PolymerElements/paper-menu#58]
There is no reference in the docs to paper-submenu. As a result you can't find it from the Polymer Element Catalogue.

**Comment by notwaldorf** [comment]
If you go to the catalog, you can see `paper-submenu` and it's docs bundled under `paper-menu`:
<img width="284" alt="screen shot 2015-11-10 at 7 04 10 pm" src="https://cloud.githubusercontent.com/assets/1369170/11082859/d79bbda0-87dd-11e5-81fa-3c6c3d9851f1.png">

Also, the demo has a submenu section as well:
<img width="449" alt="screen shot 2015-11-10 at 7 04 21 pm" src="https://cloud.githubusercontent.com/assets/1369170/11082865/e2a0f13e-87dd-11e5-8102-6e43186fb48c.png">

**Comment by akc42** [comment]
My Apologies.  I thought I had looked quite hard.  Obviously not hard enough:-(
