### ISSUE TITLE
attrForSelected is attr-for-selected

### ISSUE THREAD

**Issue by Pho3nixHun** [PolymerElements/paper-menu#67]
Documentation states attrForSelected but only attr-for-selected works.

**Comment by marcushellberg** [comment]
This is by design in Polymer, please see https://www.polymer-project.org/1.0/docs/devguide/properties.html#property-name-mapping

**Comment by bicknellr** [comment]
@Pho3nixHun, @vaadin-marcus is correct, this is expected behavior.
