### ISSUE TITLE
submenu.toggle() is not a function

### ISSUE THREAD

**Issue by dfreedm** [PolymerElements/paper-menu#81]
_From @Xeselaro on January 10, 2016 18:2_

BUG:
document.querySelector('#submenuelement').toggle() is not a function

_Copied from original issue: Polymer/polymer#3283_

**Comment by dfreedm** [comment]
Can you post a reproducible example with [jsbin](http://jsbin.com)?

This should also be posted to the [paper-menu](https://github.com/polymerelements/paper-menu) repo

**Comment by bicknellr** [comment]
@Xeselaro, please check out the [contributing guide](https://github.com/PolymerElements/paper-menu/blob/master/CONTRIBUTING.md).

**Comment by cdata** [comment]
Closing because there is no test case. Please re-open with a test case!
