### ISSUE TITLE
Mistyped detached function in paper-submenu.html

### ISSUE THREAD

**Issue by ghost** [PolymerElements/paper-menu#86]
The detached function in [paper-submenu.html - v1.2.2](https://github.com/PolymerElements/paper-menu/blob/v1.2.2/paper-submenu.html) is misspelt as `dettached`. This still appears in master as the time of writing.

**Comment by brian-cruickshank** [comment]
+1
  `dettached: function() {
        this.unlisten(this.__parent, 'iron-activate', '_onParentIronActivate');
      },`

Bug prevents unlisten from being called.
