### ISSUE TITLE
Need tap twice to make submenu closed when set paper-submenu opened=true at the first beginning.

### ISSUE THREAD

**Issue by tookit** [PolymerElements/paper-menu#88]
![image](https://cloud.githubusercontent.com/assets/149564/13072231/094b1cfa-d4d3-11e5-97b9-ba31fce4f3fa.png)

I set paper-submenu's property "opened" to true at the first beginning, then I click the menu trigger, the submenu is not closed as I expected instead of focusing on the selected submenu item, u can see from the pic.

**Comment by sounakpal** [comment]
+1

**Comment by tiffz** [comment]
I encountered this issue too.
