### ISSUE TITLE
paper-submenu jumps to first element after scrolling down then selecting

### ISSUE THREAD

**Issue by brian-cruickshank** [PolymerElements/paper-menu#89]
Please see [paper-menu/issues/17](https://github.com/PolymerElements/paper-menu/issues/17) for a good description of this problem.  I've found this occurring in v1.2.2 of the paper-menu component.  

There is a two part fix:
- comment out the content of the _onFocus method in paper-submenu.html:

```
      /**
       * Handler that is called when the menu receives focus.
       *
       * @param {FocusEvent} event A focus event.
       */
      _onFocus: function(event) {
        // this.__trigger && this.__trigger.focus();
      }
```
- in iron-menu-behavior.html's _onFocus method, increase the async function delay to 150ms or more.  See [Race condition in _onFocus](https://github.com/PolymerElements/iron-menu-behavior/issues/49) issue for more details.

**Comment by ktiedt** [comment]
Hitting this too, can we get some feeback, I am happy to convert this to a PR if the above fixes are acceptable and @brian-cruickshank doesnt have the extra cycles. 

It is rather critical for us.

**Comment by ktiedt** [comment]
Ping? Still critical, even more so actually, because now more users are complaining about it.
